/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PeersRouteImport } from './routes/peers'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyTickerRouteImport } from './routes/company.$ticker'

const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersRoute = PeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyTickerRoute = CompanyTickerRouteImport.update({
  id: '/company/$ticker',
  path: '/company/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capital': typeof CapitalRoute
  '/clusters': typeof ClustersRoute
  '/peers': typeof PeersRoute
  '/reports': typeof ReportsRoute
  '/screener': typeof ScreenerRoute
  '/sectors': typeof SectorsRoute
  '/trends': typeof TrendsRoute
  '/valuation': typeof ValuationRoute
  '/company/$ticker': typeof CompanyTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capital': typeof CapitalRoute
  '/clusters': typeof ClustersRoute
  '/peers': typeof PeersRoute
  '/reports': typeof ReportsRoute
  '/screener': typeof ScreenerRoute
  '/sectors': typeof SectorsRoute
  '/trends': typeof TrendsRoute
  '/valuation': typeof ValuationRoute
  '/company/$ticker': typeof CompanyTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capital': typeof CapitalRoute
  '/clusters': typeof ClustersRoute
  '/peers': typeof PeersRoute
  '/reports': typeof ReportsRoute
  '/screener': typeof ScreenerRoute
  '/sectors': typeof SectorsRoute
  '/trends': typeof TrendsRoute
  '/valuation': typeof ValuationRoute
  '/company/$ticker': typeof CompanyTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capital'
    | '/clusters'
    | '/peers'
    | '/reports'
    | '/screener'
    | '/sectors'
    | '/trends'
    | '/valuation'
    | '/company/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capital'
    | '/clusters'
    | '/peers'
    | '/reports'
    | '/screener'
    | '/sectors'
    | '/trends'
    | '/valuation'
    | '/company/$ticker'
  id:
    | '__root__'
    | '/'
    | '/capital'
    | '/clusters'
    | '/peers'
    | '/reports'
    | '/screener'
    | '/sectors'
    | '/trends'
    | '/valuation'
    | '/company/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapitalRoute: typeof CapitalRoute
  ClustersRoute: typeof ClustersRoute
  PeersRoute: typeof PeersRoute
  ReportsRoute: typeof ReportsRoute
  ScreenerRoute: typeof ScreenerRoute
  SectorsRoute: typeof SectorsRoute
  TrendsRoute: typeof TrendsRoute
  ValuationRoute: typeof ValuationRoute
  CompanyTickerRoute: typeof CompanyTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers': {
      id: '/peers'
      path: '/peers'
      fullPath: '/peers'
      preLoaderRoute: typeof PeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$ticker': {
      id: '/company/$ticker'
      path: '/company/$ticker'
      fullPath: '/company/$ticker'
      preLoaderRoute: typeof CompanyTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapitalRoute: CapitalRoute,
  ClustersRoute: ClustersRoute,
  PeersRoute: PeersRoute,
  ReportsRoute: ReportsRoute,
  ScreenerRoute: ScreenerRoute,
  SectorsRoute: SectorsRoute,
  TrendsRoute: TrendsRoute,
  ValuationRoute: ValuationRoute,
  CompanyTickerRoute: CompanyTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
